spring.application.name=Hobist

server.servlet.context-path=/api/v1

#db config
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.url=jdbc:postgresql://localhost:5432/Hobist
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#flyway config
spring.flyway.url=jdbc:postgresql://localhost:5432/Hobist
spring.flyway.user=myuser
spring.flyway.password=mypassword
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true

#JWT config
jwt.secret=9bcm5p36l7cregtrtoesvw23egat2bfiedogkjlohtdh5tpebd42dhqhfshfshs8q7a465sbxyh
jwt.expiration=3600000

frontend.address=http://127.0.0.1:5173

file.upload-dir=C:/Users/Marko/Desktop/Java/Hobist/uploads

#mail server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarlosarlo579@gmail.com
spring.mail.password=agjjeuqdupbgxsly
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

logging.level.org.springframework.security=DEBUG